# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-27 13:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.CharField(db_index=True, max_length=10, primary_key=True, serialize=False, unique=True)),
                ('search_terms', models.TextField(blank=True, null=True)),
                ('enzyme', models.BooleanField(default=True)),
                ('transporter', models.BooleanField(default=True)),
                ('other_proteins', models.BooleanField(default=True)),
                ('gpcr', models.BooleanField(default=True)),
                ('epigenetic_regulator', models.BooleanField(default=True)),
                ('ion_channel', models.BooleanField(default=True)),
                ('nuclear_receptor', models.BooleanField(default=True)),
                ('kd', models.BooleanField(default=True)),
                ('ic50', models.BooleanField(default=True)),
                ('ki', models.BooleanField(default=True)),
                ('potency', models.BooleanField(default=True)),
                ('mutated_target', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
