# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-22 17:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('networks', '0002_auto_20171121_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='network',
            name='data_file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
