# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-29 19:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('networks', '0003_network_data_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='network',
            name='IsRange',
            field=models.TextField(blank=True, null=True),
        ),
    ]
