# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-30 10:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('networks', '0004_network_isrange'),
    ]

    operations = [
        migrations.RenameField(
            model_name='network',
            old_name='IsRange',
            new_name='is_range',
        ),
    ]
